# Secrets pour GUDSON KPI
# Copiez ce fichier et ajoutez vos valeurs dans Streamlit Cloud

[database]
# Configuration base de données (si nécessaire)
# db_username = "your_username"
# db_password = "your_password" 
# db_host = "your_host"

[auth]
# Clés de sécurité (optionnel pour amélioration future)
# secret_key = "your-super-secret-key-here"
# jwt_secret = "your-jwt-secret"

[api]
# Clés API externes (si intégration nécessaire)
# api_key = "your_api_key"

# Note: En mode démonstration, aucun secret requis
# L'application fonctionne parfaitement sans ce fichier
